spring.datasource.url=jdbc:postgresql://centerbeam.proxy.rlwy.net:49832/railway

spring.datasource.username=postgres
spring.datasource.password=kydGrhxsrWaYMMNlqOKxDftDyUKrJjOo

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

