package com.tharun.risk_management.service;

import com.lowagie.text.*;
import com.lowagie.text.pdf.*;

import com.tharun.risk_management.entity.VesselEntity;
import com.tharun.risk_management.enums.RiskLevel;
import com.tharun.risk_management.enums.VesselStatus;
import com.tharun.risk_management.repository.VesselRepository;

import lombok.RequiredArgsConstructor;

import org.springframework.stereotype.Service;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.LocalDateTime;
import java.util.List;

@Service
@RequiredArgsConstructor
public class PdfExportService {

        private final VesselRepository vesselRepository;

        public byte[] generatePdfReport() {

                try {

                        List<VesselEntity> vessels = vesselRepository.findAll();

                        ByteArrayOutputStream out = new ByteArrayOutputStream();

                        Document document = new Document(PageSize.A4);

                        PdfWriter.getInstance(document, out);

                        document.open();

                        // =====================
                        // TITLE
                        // =====================

                        Font titleFont = new Font(Font.HELVETICA, 20, Font.BOLD, Color.WHITE);

                        PdfPTable titleTable = new PdfPTable(1);

                        titleTable.setWidthPercentage(100);

                        PdfPCell titleCell = new PdfPCell(
                                        new Phrase(
                                                        "Vessel Risk Management Report",
                                                        titleFont));

                        titleCell.setBackgroundColor(new Color(0, 100, 0));

                        titleCell.setPadding(15);

                        titleCell.setBorder(Rectangle.NO_BORDER);

                        titleCell.setHorizontalAlignment(Element.ALIGN_CENTER);

                        titleTable.addCell(titleCell);

                        document.add(titleTable);

                        document.add(new Paragraph(" "));

                        // =====================
                        // SUMMARY
                        // =====================

                        document.add(new Paragraph("Total Vessels : " + vessels.size()));

                        document.add(new Paragraph("Generated On : " + LocalDateTime.now()));

                        document.add(new Paragraph("Generated By : Vessel Risk Management System"));

                        document.add(new Paragraph("Built By : Tharun Vijay"));

                        document.add(new Paragraph(" "));

                        // =====================
                        // TABLE
                        // =====================

                        PdfPTable table = new PdfPTable(4);

                        table.setWidths(new float[] { 1f, 3f, 2f, 2f });

                        table.setWidthPercentage(100);

                        table.setSpacingBefore(10);

                        Font headerFont = new Font(Font.HELVETICA, 12, Font.BOLD, Color.WHITE);

                        Color headerColor = new Color(30, 41, 59); // Maritime Dark

                        String[] headers = {
                                        "ID",
                                        "Vessel Name",
                                        "Status",
                                        "Risk Level"
                        };

                        for (String header : headers) {

                                PdfPCell cell = new PdfPCell(
                                                new Phrase(header, headerFont));

                                cell.setBackgroundColor(headerColor);

                                cell.setPadding(10);

                                cell.setHorizontalAlignment(
                                                Element.ALIGN_CENTER);

                                table.addCell(cell);
                        }

                        for (VesselEntity vessel : vessels) {

                                table.addCell(
                                                String.valueOf(
                                                                vessel.getVesselID()));

                                table.addCell(
                                                vessel.getVesselName());

                                table.addCell(
                                                vessel.getStatus().toString());

                                PdfPCell riskCell = new PdfPCell(
                                                new Phrase(
                                                                vessel.getRiskLevel().toString()));

                                switch (vessel.getRiskLevel()) {

                                        case LOW:
                                                riskCell.setBackgroundColor(
                                                                new Color(220, 252, 231));
                                                break;

                                        case MEDIUM:
                                                riskCell.setBackgroundColor(
                                                                new Color(254, 249, 195));
                                                break;

                                        case HIGH:
                                                riskCell.setBackgroundColor(
                                                                new Color(254, 215, 170));
                                                break;

                                        case CRITICAL:
                                                riskCell.setBackgroundColor(
                                                                new Color(254, 202, 202));
                                                break;

                                        case NONE:
                                                riskCell.setBackgroundColor(
                                                                new Color(229, 231, 235));
                                                break;
                                }

                                riskCell.setHorizontalAlignment(
                                                Element.ALIGN_CENTER);

                                table.addCell(riskCell);
                        }
                        // ------------------------------- Analytics and Insights Section
                        // --------------------------------

                        long lowCount = vessels.stream()
                                        .filter(v -> v.getRiskLevel() == RiskLevel.LOW)
                                        .count();

                        long mediumCount = vessels.stream()
                                        .filter(v -> v.getRiskLevel() == RiskLevel.MEDIUM)
                                        .count();

                        long highCount = vessels.stream()
                                        .filter(v -> v.getRiskLevel() == RiskLevel.HIGH)
                                        .count();

                        long criticalCount = vessels.stream()
                                        .filter(v -> v.getRiskLevel() == RiskLevel.CRITICAL)
                                        .count();

                        long noneCount = vessels.stream()
                                        .filter(v -> v.getRiskLevel() == RiskLevel.NONE)
                                        .count();
                        document.add(table);
                        document.add(new Paragraph(" "));
                        document.add(new Paragraph(" "));

                        Font sectionFont = new Font(
                                        Font.HELVETICA,
                                        14,
                                        Font.BOLD,
                                        new Color(30, 41, 59));

                        document.add(new Paragraph("RISK ANALYTICS", sectionFont));

                        document.add(new Paragraph("Low Risk        : " + lowCount));

                        document.add(new Paragraph("Medium Risk     : " + mediumCount));

                        document.add(new Paragraph("High Risk       : " + highCount));

                        document.add(new Paragraph("Critical Risk   : " + criticalCount));

                        document.add(new Paragraph("No Risk         : " + noneCount));


                document.add(new Paragraph(" "));

                document.add(new Paragraph("STATUS ANALYTICS", sectionFont));

                for (VesselStatus status : VesselStatus.values()) {

                long count = vessels.stream()
                        .filter(v -> v.getStatus() == status)
                        .count();

                document.add(
                        new Paragraph(
                                status + " : " + count
                        )
                );
                }





                        document.close();

                        return out.toByteArray();

                } catch (Exception e) {

                        throw new RuntimeException("Failed to generate PDF", e);
                }
        }
}